@baseURL = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMmEwMDc0Zi0yOWJkLTQ1OTctOTViYS0zNWY2MmUzMWJiNDgiLCJpYXQiOjE3MDYxNDAyNzF9.KhexTjA6Y-1HMu2RGi3-V5tCdwHgTaIaRJSOkXMFBX71MYyMm3vOXIiYxSg5OeuNuO88ygUFPEvMtAmtWAixDvFHvWt-GxbeQD_SY17udDbc6i09hKYD2Ah1q_EbifUFwrnDldE-_jYUqLUfvNdZKd_UVFLLUv7Ybc6X5mfLGRgw2BxP2nR0nuCgichVAw3ggqCoP0m-if7fKpedfzs2bAqD5IkeUfAGqBv7TV5tUyHjrprpSQ1zDl4Gd2qubNmu-b5CecOY6mAXJnS77fK7FLsVxx6Y5AAycbjpWm0TNWGcoU4tfziuty7qjni6_NrV12AEufuKJKkf0K7q8hfuvg

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
	"name": "Bruno Otto",
	"email": "bruno333@gmail.com",
	"password": "12345"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
	"email": "bruno@gmail.com",
	"password": "12345"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Nova pergunta 2",
	"content": "Conteúdo da pergunta"
}

###

# @name fetch_recent_questions
GET {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}