@baseURL = http://localhost:3333
@authToken = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OGU2NGU5Zi1kMGY5LTRkZjctOTgxNi00N2M0MTg3ZjYyNzgiLCJpYXQiOjE3MDgxNzA3OTV9.hEXn5SD-REejdt50FGVeLtEtubYoqM4tWXWcf3QwKLhxSbE5yyQyhl-UUHJsB_hV9CotFJwl9Ra3oEc1Kh5nGpTTfZWov3yWrovhcidWhtAZQOSpqg4eGHskITsKpFs8uYonQqyHy1b5vCwepUxLmIf90OoAWCuS0VAIYUEs6uQA6wezTHAg3WRescsbTgoDHDoQEJtcA0uOevZl-UDpvcbgX_1g7tcc1R6cZYiDkchV41XjX6gOBuO9Fx9Wi_yrZJoGyEJOSdwvLK1QqDYeguG6kRtGUI6l4vDEC_J-2gKyYR_rpjhx0pqKTrL8CAZXOkdMyG3Z7vRPZOvraBMyGQ

# @name create_account
POST {{baseURL}}/accounts
Content-Type: application/json

{
	"name": "Bruno Otto",
	"email": "bruno@gmail.com",
	"password": "12345"
}

###

# @name authenticate
POST {{baseURL}}/sessions
Content-Type: application/json

{
	"email": "bruno@gmail.com",
	"password": "12345"
}

###

# @name create_question
POST {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
	"title": "Nova pergunta aaa",
	"content": "Conteúdo da pergunta aaa"
}

###

# @name fetch_recent_questions
GET {{baseURL}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}